catalog:
  vite: npm:@voidzero-dev/vite-plus-core@^0.1.20
  vite-plus: latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
